### ISSUE TITLE
Basic Notebooks Fail When Running with Docker on MacOS

### ISSUE THREAD

**Issue by kheuton** [yunabe/lgo#36] opened 2018-04-03 17:15 UTC
I'm running the dockerized version of lgo on MacOS 10.13.3. I've successfully launched the docker container and logged into the jupyter notebook server. However, when I try to run a cell in  the `basics.ipynb` notebook, I get the following error:
```
# /tmp/go-build175073157/libgithub.com-yunabe-lgo-sess7b2274696d65223a313532323737353439343231353335333930307d-exec1.so
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
collect2: fatal error: ld terminated with signal 4 [Illegal instruction]
compilation terminated.

Failed to build a shared library of github.com/yunabe/lgo/sess7b2274696d65223a313532323737353439343231353335333930307d/exec1: exit status 2
```

**Comment by yunabe** [comment] 2018-04-03 23:09
I could not reproduce this issue with the latest docker image. Can you share the command you ran?
Also, please double check you are using the latest docker image.

```
docker pull yunabe/lgo:latest
docker-compose build (if you use docker-compose.yml in docker/jupyter)
```

My environment:
```
OSX: 10.13.3
Docker: 18.03.0-ce
```

**Comment by yunabe** [comment] 2018-05-11 08:18
I'm closing this issue because there is no update. Feel free to reopen it if you still have the problem.

**Closed by yunabe** 2018-05-11 08:18 UTC
