### ISSUE TITLE
Build error: reloc 10 (R_CALLARM64) to non-elf symbol type

### ISSUE THREAD

**Issue by maximtrp** [yunabe/lgo#79] opened 2019-03-09 09:48 UTC
I'm trying to install `lgo` and get the following error:

```bash
$ go get github.com/yunabe/lgo/cmd/lgo && go get -d github.com/yunabe/lgo/cmd/lgo-internal
$ lgo install

2019/03/09 12:41:38 Install lgo to /home/maxim/go/lgo
2019/03/09 12:41:38 Building libstd.so
# /tmp/go-build820042594/b194/libstd.so
Erratum 835769 found and fixed at "/tmp/go-link-237765660/000025.o", section 50, offset 0x0000113c.
Erratum 835769 found and fixed at "/tmp/go-link-237765660/000025.o", section 50, offset 0x000057c0.
Erratum 835769 found and fixed at "/tmp/go-link-237765660/000025.o", section 50, offset 0x0000fd88.
Erratum 835769 found and fixed at "/tmp/go-link-237765660/000025.o", section 50, offset 0x0000fedc.
Erratum 835769 found and fixed at "/tmp/go-link-237765660/000025.o", section 50, offset 0x0000113c.
Erratum 835769 found and fixed at "/tmp/go-link-237765660/000025.o", section 50, offset 0x000057c0.
Erratum 835769 found and fixed at "/tmp/go-link-237765660/000025.o", section 50, offset 0x0000fd88.
Erratum 835769 found and fixed at "/tmp/go-link-237765660/000025.o", section 50, offset 0x0000fedc.
2019/03/09 12:41:48 Building lgo core package
# /tmp/go-build086705797/b196/libstd.so
Erratum 835769 found and fixed at "/tmp/go-link-530501271/000025.o", section 50, offset 0x0000113c.
Erratum 835769 found and fixed at "/tmp/go-link-530501271/000025.o", section 50, offset 0x000057c0.
Erratum 835769 found and fixed at "/tmp/go-link-530501271/000025.o", section 50, offset 0x0000fd88.
Erratum 835769 found and fixed at "/tmp/go-link-530501271/000025.o", section 50, offset 0x0000fedc.
Erratum 835769 found and fixed at "/tmp/go-link-530501271/000025.o", section 50, offset 0x0000113c.
Erratum 835769 found and fixed at "/tmp/go-link-530501271/000025.o", section 50, offset 0x000057c0.
Erratum 835769 found and fixed at "/tmp/go-link-530501271/000025.o", section 50, offset 0x0000fd88.
Erratum 835769 found and fixed at "/tmp/go-link-530501271/000025.o", section 50, offset 0x0000fedc.
2019/03/09 12:42:02 Building third-party packages in $GOPATH
2019/03/09 12:42:02 Installing lgo-internal
# /tmp/go-build071371341/b214/libstd.so
Erratum 835769 found and fixed at "/tmp/go-link-376813173/000025.o", section 50, offset 0x0000113c.
Erratum 835769 found and fixed at "/tmp/go-link-376813173/000025.o", section 50, offset 0x000057c0.
Erratum 835769 found and fixed at "/tmp/go-link-376813173/000025.o", section 50, offset 0x0000fd88.
Erratum 835769 found and fixed at "/tmp/go-link-376813173/000025.o", section 50, offset 0x0000fedc.
Erratum 835769 found and fixed at "/tmp/go-link-376813173/000025.o", section 50, offset 0x0000113c.
Erratum 835769 found and fixed at "/tmp/go-link-376813173/000025.o", section 50, offset 0x000057c0.
Erratum 835769 found and fixed at "/tmp/go-link-376813173/000025.o", section 50, offset 0x0000fd88.
Erratum 835769 found and fixed at "/tmp/go-link-376813173/000025.o", section 50, offset 0x0000fedc.
# github.com/yunabe/lgo/cmd/lgo-internal
type..MO7lsdMr: reloc 10 (R_CALLARM64) to non-elf symbol type..FEeY9FdU (outer=type..FEeY9FdU) 49 (SABIALIAS)
2019/03/09 12:42:52 Failed to build lgo-internal: exit status 2
```

`go version` output:
```
go version go1.12 linux/arm64
```

`uname -a`:
```
Linux odroidc2 3.16.63-1-ARCH #1 SMP PREEMPT Sat Feb 23 12:06:13 MST 2019 aarch64 GNU/Linux
```

**Comment by yunabe** [comment] 2019-03-22 08:43
Duplicate of #82

**Closed** 2024-05-17 10:51 UTC
